name: Release binaries

on:
  release:
    types: [created]

jobs:
  amd64-releases-matrix:
    name: Release Go Binary (amd64)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goversion: ["1.17"]
        goos: [linux, windows, darwin]
        goarch: [amd64]
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.16
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goversion: ${{ matrix.goversion }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "."
          binary_name: "ssl-handshake"
          ldflags: "-s -w"
          extra_files: LICENSE README.md

  arm64-releases-matrix:
    name: Release Go Binary (arm64)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goversion: ["1.17"]
        goos: [linux, darwin]
        goarch: [arm64]
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.16
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goversion: ${{ matrix.goversion }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "."
          binary_name: "ssl-handshake"
          ldflags: "-s -w"
          extra_files: LICENSE README.md